FROM python:3.9-slim

# Install Streamlit with no cache to minimize image size
RUN pip install streamlit

# Copy application file to the container
COPY app.py /app/app.py

# Set the working directory
WORKDIR /app

# Expose Streamlit port
EXPOSE 8501

# Default command to run the application
CMD ["streamlit", "run", "app.py", "--server.address=0.0.0.0", "--server.port=8501"]

