services:
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    ports:
      - "5001:5001" # MLflow يعمل الآن على المنفذ 5001

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501" # Streamlit على المنفذ الافتراضي 8501
