FROM python:3.9-slim

# Install MLflow with no cache to minimize image size
RUN pip install mlflow

# Set the working directory
WORKDIR /app

# Expose MLflow port
EXPOSE 5001

# Default command to run the MLflow server
CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5001"]
